### ISSUE TITLE
YouTube 支持？

### ISSUE THREAD

**Issue by JuanitoFatas** [DeathKing/Learning-SICP#27]
不好意思請問下，字幕會打算做支持 YouTube 的格式嗎？

**Comment by DeathKing** [comment]
@JuanitoFatas  拖了这么久，终于给上传了……需不需要做正体中文版的字幕？

https://www.youtube.com/playlist?list=PLkEwH_Z2WOlppy8oUfrGwFVlOuKyo3RO_

**Comment by JuanitoFatas** [comment]
:clap: :clap: :clap:  我覺得把簡體中文做完，再來考慮轉成繁體。
