### ISSUE TITLE
需要一个GitHub Page

### ISSUE THREAD

**Issue by DeathKing** [DeathKing/Learning-SICP#44]
有能力的同学请认领。

**Comment by noname007** [comment]
搞到什么程度？

**Comment by DeathKing** [comment]
@noname007 理论上来说，应该有一个页面用于放这些视频的索引（或者说目录，index），然后每个视频有个单独的页面，加上多说或者disqus之类的评论系统。然后还有个页面，用于索引其它有用的学习资料（Awesome page）。其实内容不复杂，关键是想做成 SICP 红紫色的配色的主题，又不刺眼，这个比较难。

**Comment by zhangsoledad** [comment]
用jekyll倒是方便 ui苦手不太会写css 也抽不出时间 你发到各个社区里吧 应该会有人响应的

**Comment by noname007** [comment]
@zhangsoledad 用hexo 一类的东西，或许更好一些。

**Comment by noname007** [comment]
@DeathKing  用hexo yinwang主题稍微改造了一个demo。 

预览地址 http://noname007.github.io/Learning-SICP/

repo https://github.com/noname007/-Learning-SICP-hexo

**Comment by DeathKing** [comment]
@noname007 额。如果只是放 README 的话，其实我感觉项目的README就够了，不用用 GitHub Page。主要想做一个综合性一点的 site ，这是个非常累的活。

**Comment by leiming** [comment]
@DeathKing 方便的话，【综合性一点的 site】包含哪些？

- 视频的索引，OK
- disqus，也OK
- 紫红色主题，问题不大

还需要添加什么？

**Comment by Yensan** [comment]
不会CSS，为认领的人点赞！
另外建议你们一切从简，但是重视内容。程序猿需要简洁，不需要过分的美观……

**Comment by DeathKing** [comment]
@leiming 目前应该就是这样了吧，最主要是想保证整个 Site 比较符合 SICP 的这种配色。
![sicp_1st_cover](https://user-images.githubusercontent.com/895809/34156020-6abb2bf8-e4f6-11e7-9f31-ba276ec4fcd7.jpg)
![sicp](https://user-images.githubusercontent.com/895809/34156146-edd28130-e4f6-11e7-94a7-5072d6a16b3d.jpg)

**Comment by Rezhe** [comment]
我可以用Jekyll做一个XD

**Comment by DeathKing** [comment]
ref: https://learningsicp.github.io
