### ISSUE TITLE
任务列表课程名字

### ISSUE THREAD

**Issue by ChangZhongWei** [DeathKing/Learning-SICP#59]
可以把任务列表中每个任务的名字写上么？
这样可以根据个人兴趣去翻译~ 
觉得后面的章节会越来越慢

**Comment by Windfarer** [comment]
看这个吧 #33 ，每个lecture的主题都列出来了。

**Comment by ChangZhongWei** [comment]
sorry~~~~(>_<)~~~~

**Comment by DeathKing** [comment]
@ChangZhongWei  其实现在翻译得还挺多的。关键是我校订的速度跟不上。
