### ISSUE TITLE
哔哩哔哩已更新Lec6a

### ISSUE THREAD

**Issue by tyfulcrum** [DeathKing/Learning-SICP#67]
我是哔哩哔哩的搬运工，已经跟进更新。请在README添加Lec6a的哔哩哔哩链接，即https://www.bilibili.com/video/av8515129/index_11.html 。

**Comment by DeathKing** [comment]
其它几个已经上传了MP4的课程，也麻烦UP主能搬一下。
Youku好像有二压，而且也有水印。

**Comment by tyfulcrum** [comment]
@DeathKing 我这次上传的时候才发现有压好的mp4版本，之前都是自己压字幕来着，应该没区别吧？

**Comment by liunian1004** [comment]
good job。

**Comment by DeathKing** [comment]
@tyfulcrum 应该没问题。我可能是记错了，之前有个Up主是直接从优酷搬的。
