### ISSUE TITLE
麻烦问下待校对的什么时候能校对好呢

### ISSUE THREAD

**Issue by slidoooor** [DeathKing/Learning-SICP#69]
多谢啦

**Comment by Windfarer** [comment]
（禁止催稿，233

**Comment by motecshine** [comment]
现在的群还能加进去么

**Comment by DeathKing** [comment]
@slidoooor 估算了一下 粗校100行就要1小时，细校订和后期时间另算，其实还是挺麻烦的。现在重新拟定了工作计划，进度会加快一点，主要是用业余时间在做这个项目，所以有时候会很拖。
@motecshine 能。进群有一个很简单的问题需要回答一下。

**Comment by slidoooor** [comment]
@DeathKing 多谢啦，不急不急，就是想知道进度，嘿嘿，辛苦你们了
