### ISSUE TITLE
哔哩哔哩已更新Lec6b、7a及7b

### ISSUE THREAD

**Issue by tyfulcrum** [DeathKing/Learning-SICP#71]
我是哔哩哔哩的搬运工，已经跟进更新，链接如下：
Lec6b
https://www.bilibili.com/video/av8515129/index_12.html
Lec7a
https://www.bilibili.com/video/av8515129/index_13.html
Lec7b
https://www.bilibili.com/video/av8515129/index_14.html

**Comment by DeathKing** [comment]
Well done.
