### ISSUE TITLE
原始视频的高清版本，不知道你们需要不

### ISSUE THREAD

**Issue by songjinghe** [DeathKing/Learning-SICP#90]
我看你们的视频大小都200~300MB左右，我看有时候黑板上的字不是很清楚。我大概5年前从外网扒了一套高清版本MPG格式的，黑板上的字确实要清楚一些（每集大概1～2GB左右）。我不知道是不是原版。如果能压一个清晰的出来就好了。

链接: https://pan.baidu.com/s/1dGyWXwGL6jzbfHK_d3ypuA
提取码: xhe1

**Comment by DeathKing** [comment]
之前我在 archive.org 上好像看到过类似的版本，这个版本好像是因为编码方式的原因，导致特别大，而且有些视频的纵横比还有问题。

放出来的版本是因为用 H.264 两次编码，大小方面肯定有所优化。

**Comment by songjinghe** [comment]
我个人认为这个版本黑板上的字更清楚。大家可以自行对比一下，顺便帮忙给个反馈。如果大家普遍认为清晰度高的话（可以直接给本条回复加个表情），建议用这个版本重新压一遍。

如果没觉得更清楚的话，就关了吧。
