### ISSUE TITLE
GoogleDrive内视频1a-2b的文件名问题

### ISSUE THREAD

**Issue by yangrq** [DeathKing/Learning-SICP#93]
本应Learning-SICP出现的位置出现不明字符？

**Comment by DeathKing** [comment]
@yangrq 这之中有一些历史原因。

本课程最早由哈尔滨工业大学IBM技术中心（FoOTOo实验室）牵头组织翻译，由哈尔滨工业大学清影PT（HITPT）提供技术支持。

后期为了统筹整个翻译项目，才以 Learning-SICP 的名义发布视频。

你可以在 README 文件的开头处看到以上提及的两个组织！

**Comment by yangrq** [comment]
略有逼死强迫症之感
